name: release
on:
   pull_request:
      branches:
      - main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout
         uses: actions/checkout@v2
         with:
            fetch-depth: 0
      -  name: GitTools
         uses: GitTools/actions/gitversion/setup@v0.9.9
         with:
            versionSpec: 5.x
            includePrerelease: false
      -  name: Display GitVersion config
         uses: gittools/actions/gitversion/execute@v0.9.9
         with:
            additionalArguments: /showConfig
      -  name: Determine Version
         uses: gittools/actions/gitversion/execute@v0.9.9
      -  name: Display SemVer
         run: |
            echo "SemVer: $GITVERSION_SEMVER"
      -  uses: ncipollo/release-action@v1
         with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ steps.gitversion.outputs.SemVer }}