name: release
on:
   push:
      branches:
      - semver
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout
         uses: actions/checkout@v2
         with:
            fetch-depth: 0
      -  name: GitTools
         uses: GitTools/actions/gitversion/setup@v0.9.9
         with:
            versionSpec: 5.x
            includePrerelease: false
      -  name: Display GitVersion config
         uses: gittools/actions/gitversion/execute@v0.9.9
         with:
            additionalArguments: /showConfig
      -  name: Determine Version
         uses: gittools/actions/gitversion/execute@v0.9.9
      -  name: Display SemVer
         run: |
            echo "SemVer: $GITVERSION_SEMVER"
#      -  name: Create Release
# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:38 :#         uses: actions/create-release@v1
# Was at begin of line:39 :#         with:
# Was at begin of line:40 :#            tag_name: ${{ steps.gitversion.outputs.SemVer }}