name: release
on:
   push:
      branches:
      - semver
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Display tree
         run: |
            tree /home/runner/work/
      -  name: Checkout
         uses: actions/checkout@v2
         with:
            fetch-depth: 0
      -  name: Display tree
         run: |
            tree /home/runner/work/
      -  name: GitTools
         uses: GitTools/actions@v0.9.9
      -  name: Display tree
         run: |
            tree /home/runner/work/
      -  name: Display GitVersion config
         uses: gittools/actions/gitversion/execute@v0.9.9
         with:
            additionalArguments: /showConfig
      -  name: Determine Version
         uses: gittools/actions/gitversion/execute@v0.9.9
      -  name: Display SemVer
         run: |
            echo "SemVer: $GITVERSION_SEMVER"
#      -  name: Create Release
#         uses: actions/create-release@v1
#         with:
#            tag_name: ${{ steps.gitversion.outputs.SemVer }}